# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1218, 765)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 70))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 68))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/icons/icon_menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("aaaa")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(212, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_6.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"background-color: rgb(72, 72, 72);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(150, 212))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(273, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Interact1 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_Interact1.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Interact1.setFont(font)
        self.pushButton_Interact1.setStyleSheet("QPushButton#pushButton_Interact1:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_Interact1:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Interact1.setIcon(icon1)
        self.pushButton_Interact1.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Interact1.setObjectName("pushButton_Interact1")
        self.gridLayout.addWidget(self.pushButton_Interact1, 8, 0, 1, 1)
        self.pushButton_ThreeBut = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_ThreeBut.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_ThreeBut.setFont(font)
        self.pushButton_ThreeBut.setStyleSheet("QPushButton#pushButton_ThreeBut:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_ThreeBut:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-lock-unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ThreeBut.setIcon(icon2)
        self.pushButton_ThreeBut.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_ThreeBut.setObjectName("pushButton_ThreeBut")
        self.gridLayout.addWidget(self.pushButton_ThreeBut, 6, 0, 1, 1)
        self.pushButton_SearchFeature = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_SearchFeature.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_SearchFeature.setFont(font)
        self.pushButton_SearchFeature.setStyleSheet("QPushButton#pushButton_SearchFeature:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_SearchFeature:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SearchFeature.setIcon(icon3)
        self.pushButton_SearchFeature.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_SearchFeature.setObjectName("pushButton_SearchFeature")
        self.gridLayout.addWidget(self.pushButton_SearchFeature, 3, 0, 1, 1)
        self.pushButton_PipeLine = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_PipeLine.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_PipeLine.setFont(font)
        self.pushButton_PipeLine.setStyleSheet("QPushButton#pushButton_PipeLine:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_PipeLine:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-cursor-move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_PipeLine.setIcon(icon4)
        self.pushButton_PipeLine.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_PipeLine.setObjectName("pushButton_PipeLine")
        self.gridLayout.addWidget(self.pushButton_PipeLine, 2, 0, 1, 1)
        self.pushButton_Overview = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_Overview.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Overview.setFont(font)
        self.pushButton_Overview.setStyleSheet("QPushButton#pushButton_Overview:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_Overview:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-lightbulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Overview.setIcon(icon5)
        self.pushButton_Overview.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Overview.setObjectName("pushButton_Overview")
        self.gridLayout.addWidget(self.pushButton_Overview, 0, 0, 1, 1)
        self.pushButton_PipeLine_2 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_PipeLine_2.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_PipeLine_2.setFont(font)
        self.pushButton_PipeLine_2.setStyleSheet("QPushButton#pushButton_PipeLine_2:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_PipeLine_2:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-3d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_PipeLine_2.setIcon(icon6)
        self.pushButton_PipeLine_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_PipeLine_2.setObjectName("pushButton_PipeLine_2")
        self.gridLayout.addWidget(self.pushButton_PipeLine_2, 1, 0, 1, 1)
        self.pushButton_AdHTable = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_AdHTable.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_AdHTable.setFont(font)
        self.pushButton_AdHTable.setStyleSheet("QPushButton#pushButton_AdHTable:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_AdHTable:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icon/icons/cil-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_AdHTable.setIcon(icon7)
        self.pushButton_AdHTable.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_AdHTable.setObjectName("pushButton_AdHTable")
        self.gridLayout.addWidget(self.pushButton_AdHTable, 4, 0, 1, 1)
        self.pushButton_Interact2 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_Interact2.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Interact2.setFont(font)
        self.pushButton_Interact2.setStyleSheet("QPushButton#pushButton_Interact2:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_Interact2:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.pushButton_Interact2.setIcon(icon1)
        self.pushButton_Interact2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Interact2.setObjectName("pushButton_Interact2")
        self.gridLayout.addWidget(self.pushButton_Interact2, 9, 0, 1, 1)
        self.pushButton_AddAction = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_AddAction.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_AddAction.setFont(font)
        self.pushButton_AddAction.setStyleSheet("QPushButton#pushButton_AddAction:hover{\n"
"    background-color: rgb(85, 0, 127);\n"
"    color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_AddAction:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.pushButton_AddAction.setIcon(icon7)
        self.pushButton_AddAction.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_AddAction.setObjectName("pushButton_AddAction")
        self.gridLayout.addWidget(self.pushButton_AddAction, 5, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.verticalLayout_4.addWidget(self.frame_10, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(366, 653))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_12.addWidget(self.textEdit_2)
        self.label_5 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("cac-mau-canh-tay-robot-cong-nghiep.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.page_1)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_4.addWidget(self.textEdit)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("main_interface.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("luu_do.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Search_feature.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.page_5)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Feature_DH.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("edit,Execute,delete.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.page_7)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Add_feature.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.page_8)
        self.label_8.setText("")
        self.label_8.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_8.setPixmap(QtGui.QPixmap("tt1.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.page_9)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("tt_2.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_15.addWidget(self.label_9)
        self.stackedWidget.addWidget(self.page_9)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Interface Help"))
        self.pushButton.setText(_translate("Dialog", " MENU"))
        self.lineEdit.setText(_translate("Dialog", "Documentation"))
        self.lineEdit_2.setText(_translate("Dialog", "CONTENTS"))
        self.pushButton_Interact1.setText(_translate("Dialog", "    Interact 1           "))
        self.pushButton_ThreeBut.setText(_translate("Dialog", "   Excute,Delete,Edit"))
        self.pushButton_SearchFeature.setText(_translate("Dialog", "    Search feature    "))
        self.pushButton_PipeLine.setText(_translate("Dialog", "    Pipe line             "))
        self.pushButton_Overview.setText(_translate("Dialog", "    OverView           "))
        self.pushButton_PipeLine_2.setText(_translate("Dialog", "    Main Interface    "))
        self.pushButton_AdHTable.setText(_translate("Dialog", "    Add DH table      "))
        self.pushButton_Interact2.setText(_translate("Dialog", "    Interact 2           "))
        self.pushButton_AddAction.setText(_translate("Dialog", "    Add Action          "))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:#ffffff;\"><a name=\"docs-internal-guid-55c264d8-7fff-c6d3-3f85-be18905cb218\"></a><span style=\" font-family:\'Times New Roman\'; font-size:18pt; font-weight:696; color:#000000; background-color:transparent;\">G</span><span style=\" font-family:\'Times New Roman\'; font-size:18pt; font-weight:696; color:#000000; background-color:transparent;\">IAO DIỆN MÔ PHỎNG ĐIỀU KHIỂN CÁNH TAY ROBOT </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"><br /></span></p></body></html>"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Tổng quan giải pháp của đề tài: </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Khái niệm về Arm Robot:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"docs-internal-guid-4d83ffd8-7fff-0b99-5acc-236f2ab8ff8e\"></a><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000; background-color:transparent;\">A</span><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000; background-color:transparent;\">rm robot (hay gọi là cánh tay robot) là một loại cánh tay cơ học, thường được lập trình, có chức năng tương tự như cánh tay người; cánh tay có thể là tổng của cơ chế hoặc có thể là một phần của robot phức tạp hơn. Các liên kết của một bộ điều khiển như vậy được kết nối bởi các khớp cho phép chuyển động quay hoặc dịch chuyển tịnh tiến.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:6pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:6pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Những khó khăn khi làm việc với Arm robot:</span><span style=\" font-size:6pt; font-weight:600;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Khả năng kết hợp với con người còn hạn chế với  những điều khiển nút ấn.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Sai sót chưa tối ưu khi chưa có màn hình theo dõi cụ thể.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Tương tác người – Arm robot chưa linh hoạt, tốn nhiều  thời gian.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Giải pháp đề xuất của đề:</span><span style=\" font-size:6pt; font-weight:600;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Giao diện được nhóm thiết kế nhằm cải thiện các khó khăn mà khi làm việc gặp phải với Arm Robot, giao diện tạo ra giúp người dùng trực tiếp tương tác với Robot và theo dõi điều khiển với các tính năng:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:6pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans Symbols\'; font-size:14pt; color:#000000;\">✔ </span><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Tạo ra không gian làm việc từ dữ liệu cài đặt đầu vào của người dùng.</span><span style=\" font-family:\'Times New Roman\'; font-size:6pt; color:#000000;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:6pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans Symbols\'; font-size:14pt; color:#000000;\">✔</span><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Mô phỏng được chuyển động của Arm robot trong không gian làm việc.</span><span style=\" font-size:8pt;\"> </span><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans Symbols\'; font-size:14pt; color:#000000;\">✔</span><span style=\" font-family:\'Times New Roman\'; font-size:14pt; color:#000000;\">Vẽ quỹ đạo chuyển động của điểm cuối, cho phép người dùng điều khiển cánh tay bằng điều khiển từng thông số khớp.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600;\"><br /></p></body></html>"))
import Icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
